/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=ApiWorkerBindings src/worker-bindings.d.ts` (hash: 9c4bb42cd84ddecac14a40dbac7a3207)
interface __BaseEnv_ApiWorkerBindings {
	LINE_WEBHOOK_DB: D1Database;
	API_ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ApiWorkerBindings {}
}
interface ApiWorkerBindings extends __BaseEnv_ApiWorkerBindings {}
