/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/expenses/form-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 支出フォームのメンバーと操作本人を取得 */
        get: operations["getExpenseFormOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 月次の支払い一覧を取得 */
        get: operations["listExpensesByMonth"];
        put?: never;
        /** 支払いを作成 */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 支払い詳細を取得 */
        get: operations["getExpense"];
        /** 支払いを更新 */
        put: operations["updateExpense"];
        post?: never;
        /** 支払いを削除 */
        delete: operations["deleteExpense"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 削除した支払いを復元 */
        post: operations["restoreExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 月次精算サマリを取得 */
        get: operations["getSettlementByMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Expense: {
            /** @example exp_123 */
            id: string;
            /** @example user_1 */
            userId: string;
            /** @example げんき */
            userName?: string;
            /**
             * Format: date
             * @example 2026-02-15
             */
            date: string;
            /** @example 1200 */
            price: number;
            /** @example food */
            category: string;
            /** @example lunch */
            memo?: string | null;
            /** @example 1 */
            version: number;
        };
        ExpenseFormOptions: {
            actorId: string;
            members: {
                id: string;
                displayName: string;
            }[];
        };
        CreateExpenseRequest: {
            /** @description Registered household payer ID; defaults to the actor on create and retains the payer on update. */
            userId?: string;
            /**
             * Format: date
             * @example 2026-02-15
             */
            date: string;
            /** @example 1200 */
            price: number;
            /** @example food */
            category: string;
            /** @example lunch */
            memo?: string | null;
        };
        UpdateExpenseRequest: {
            /** @description Registered household payer ID; defaults to the actor on create and retains the payer on update. */
            userId?: string;
            /**
             * Format: date
             * @example 2026-02-15
             */
            date?: string;
            /** @example 1200 */
            price?: number;
            /** @example food */
            category?: string;
            /** @example lunch */
            memo?: string | null;
            /** @example 1 */
            version: number;
        };
        ListExpensesResponse: {
            expenses: components["schemas"]["Expense"][];
        };
        ExpenseDetailResponse: {
            expense: components["schemas"]["Expense"];
            /** @example false */
            deleted: boolean;
        };
        SettlementSummaryResponse: {
            /** @example 2026-06 */
            month: string;
            /** @example 14000 */
            householdTotal: number;
            userTotals: components["schemas"]["UserMonthlyTotal"][];
            /** @example 6000 */
            difference: number;
            settlement: components["schemas"]["MonthlySettlement"];
        };
        UserMonthlyTotal: {
            /** @example user_1 */
            userId: string;
            /** @example A */
            displayName: string;
            /** @example 10000 */
            total: number;
        };
        MonthlySettlement: {
            /** @example user_2 */
            fromUserId: string | null;
            /** @example user_1 */
            toUserId: string | null;
            /** @example 3000 */
            amount: number;
        };
        ErrorResponse: {
            /** @example Invalid request */
            message: string;
            details: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description リクエスト不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Invalid request",
                 *       "details": {
                 *         "field": "date",
                 *         "reason": "must be YYYY-MM",
                 *         "action": "入力内容を確認して、もう一度お試しください"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 認証エラー */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 権限エラー */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "このLINEユーザーは家計簿に登録されていません",
                 *       "details": {
                 *         "code": "USER_NOT_REGISTERED",
                 *         "action": "初回登録で使うユーザーを選択してください"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 認証基盤または外部連携の一時エラー */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "ユーザー情報を確認できません",
                 *       "details": {
                 *         "code": "AUTH_UNAVAILABLE",
                 *         "action": "家計簿のユーザー情報を読み込めません。時間をおいて再度お試しください。解消しない場合は管理者に連絡してください"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 対象なし */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Expense not found",
                 *       "details": {
                 *         "id": "exp_123",
                 *         "action": "一覧に戻って最新の支出を確認してください"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 更新競合 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Expense version conflict",
                 *       "details": {
                 *         "id": "exp_123",
                 *         "expectedVersion": 3,
                 *         "actualVersion": 4,
                 *         "action": "再読み込みして最新の内容を確認してから、もう一度お試しください"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description サーバーエラー */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Internal server error",
                 *       "details": {
                 *         "action": "時間をおいて再度お試しください。解消しない場合は管理者に連絡してください"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Expense ID */
        ExpenseId: string;
        /** @description Retry-safe mutation key used to deduplicate retried create, update, and delete requests. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getExpenseFormOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered household members without LINE identifiers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseFormOptions"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listExpensesByMonth: {
        parameters: {
            query: {
                /** @description 対象年月（YYYY-MM） */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExpensesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Retry-safe mutation key used to deduplicate retried create, update, and delete requests. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense ID */
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Retry-safe mutation key used to deduplicate retried create, update, and delete requests. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Expense ID */
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Retry-safe mutation key used to deduplicate retried create, update, and delete requests. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Expense ID */
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    restoreExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Retry-safe mutation key used to deduplicate retried create, update, and delete requests. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Expense ID */
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 復元成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSettlementByMonth: {
        parameters: {
            query: {
                /** @description 対象年月（YYYY-MM） */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementSummaryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
